// Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const CREATE_NEW_USER_SUCCESS = 'CREATE_NEW_USER_SUCCESS';
export const CREATE_NEW_USER_FAIL = 'CREATE_NEW_USER_FAIL';
export const FETCH_USER_DB_INFO = 'FETCH_USER_DB_INFO';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SET_USER_AUTH_INFO = 'SET_USER_AUTH_INFO';
export const CLEAR_USER_AUTH_INFO = 'CLEAR_USER_AUTH_INFO';
export const CLEAR_GAME_INFO = 'CLEAR_GAME_INFO';
export const CLEAR_BEERS_INFO = 'CLEAR_BEERS_INFO';
export const CLEAR_USER_DB_INFO = 'CLEAR_USER_DB_INFO';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

// Beer Data
export const FETCH_BEER_INFO = 'FETCH_BEER_INFO';
export const FETCH_GAME_INFO = 'FETCH_GAME_INFO';
export const ADD_NEW_BEER_SUCCESS = 'ADD_NEW_BEER_SUCCESS';
export const ADD_NEW_BEER_FAIL = 'ADD_NEW_BEER_FAIL';

// Vote
export const VOTES_SUBMIT_SUCCESS = 'VOTE_SUBMIT_SUCCESS';
export const VOTES_SUBMIT_FAIL = 'VOTE_SUBMIT_FAIL';
